name: CD

on:
  workflow_dispatch:
    inputs:
        version:
            description: 'Version to update'
            required: true
            type: string

jobs:
  update-firefox:
    name: Update firefox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Download latest xpi
        run: |
          curl -o dist/firefox/${{ inputs.version }}.xpi https://github.com/NIAEFEUP/nitsig/releases/download/v${{ inputs.version }}/firefox.xpi

      - name: Update manifest
        run: |
          jq '."addons"."nitsig@ni.fe.up.pt"."updates" += [{ "version": "${{ inputs.version }}", "update_link": "https://ni.fe.up.pt/nitsig/firefox/${{ inputs.version }}.xpi" }]' dist/firefox/updates.json

      - name: Commit and push
        uses: actions-js/push@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Update firefox to ${{ inputs.version }}
